name: 'AWS SSM Deploy'
description: 'Deploy to EC2 instance using AWS SSM'

inputs:
  instance-id:
    description: 'EC2 Instance ID'
    required: true
  working-directory:
    description: 'Working directory on EC2'
    required: true
  script-name:
    description: 'Script name to execute'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Deploy using AWS SSM
      shell: bash
      run: |
        COMMAND_ID=$(aws ssm send-command \
          --targets "Key=instanceids,Values=${{ inputs.instance-id }}" \
          --document-name "AWS-RunShellScript" \
          --parameters commands=["cd ${{ inputs.working-directory }} && ./${{ inputs.script-name }}"] \
          --output text \
          --query "Command.CommandId")

        echo "🚀 Started deployment with command ID: $COMMAND_ID"

        echo "🕒 Waiting for command to complete..."
        aws ssm wait command-executed \
          --command-id "$COMMAND_ID" \
          --instance-id "${{ inputs.instance-id }}"

        COMMAND_STATUS=$(aws ssm get-command-invocation \
          --command-id "$COMMAND_ID" \
          --instance-id "${{ inputs.instance-id }}" \
          --query "Status" \
          --output text)

        if [ "$COMMAND_STATUS" != "Success" ]; then
          echo "🔴 Deployment failed with status: $COMMAND_STATUS"
          exit 1
        fi
